### ISSUE TITLE
Examples do not work

### ISSUE THREAD

**Issue by kevinjohncutler** [VasylVaskivskyi/microaligner#1]
The listed examples using microaligner give errors. For feature alignment, I get a `list index out of range` error. For optic flow alginment, I get `local variable 'm_flow' referenced before assignment`. My input for `im1` and `im2` are 2D grayscale images.

**Comment by VasylVaskivskyi** [comment]
Hi @kevinjohncutler, thank you for reporting the issue, could you please share more info about what you tried to do, and input images if possible

**Comment by VasylVaskivskyi** [comment]
@kevinjohncutler I've made a tutorial on how to use microaligner.
Please have a look if you are still interested
https://colab.research.google.com/drive/1ZLKRXcOHZ2nmKUoCb52u4tYz8Km2udZ2?usp=share_link
