### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by brian1000** [VasylVaskivskyi/microaligner#2]
Hello! I'm a newbie with computers and just want to try your software to align two images as a test. I created a new virtual environment with Anaconda and performed `pip install microaligner`. Within the env I have a jupyter notebook in which I'd like to run the analysis pipeline, but I don't know how to get started! What do I do with config.yaml files and environment.yaml files? 

I started up a cell and copied over your code for feature-based registration. 

```
`from microaligner import FeatureRegistrator, transform_img_with_tmat
freg = FeatureRegistrator()
freg.ref_img = img1
freg.mov_img = img2
transformation_matrix = freg.register()

img2_feature_reg_aligned = transform_img_with_tmat(img2, img2.shape, transformation_matrix)` 
```

Where am I supposed to set the paths to the two images I want to register? I have a feeling that setting those paths won't do much to make the code run as intended from there. Could you take me through all the basic steps for setting this up if you have time? 

For reference, I'm on Windows 10 & running python -v 3.9.16 inside the env. Thanks!

**Comment by VasylVaskivskyi** [comment]
Hello @brian1000, I can make a google colab notebook for you with an exmaple if that would help.

**Comment by VasylVaskivskyi** [comment]
@brian1000 I just made a tutorial for you on google colab. Please check if everything is understandable. If you have any questions I will gladly answer them.

https://colab.research.google.com/drive/1ZLKRXcOHZ2nmKUoCb52u4tYz8Km2udZ2?usp=share_link

**Comment by brian1000** [comment]
@VasylVaskivskyi 

This is really helpful! Thank you for putting this together @VasylVaskivskyi. This was exactly what I need.
